### ISSUE TITLE
Specify dplyr::summarise() in plot_HLA_Diversity function

### ISSUE THREAD

**Issue by iseultj** [yang-luo-lab/HLADiversity#2]
Hi, I was trying out your package and noticed I was getting some error messages with the default plot_HLA_Diversity function 
```
Error in `n()`:
! Must only be used inside data-masking verbs like `mutate()`, `filter()`, and `group_by()`.
```

This is easily fixed by specifying the function to use should be dplyr::summarise(), so the new function would be:

```
plot_HLA_Diversity <-  function(hped, gene = "A", ntop = 2){
   if(!require(pacman)) install.packages("pacman")
  pacman::p_load(stringr, plyr, RColorBrewer, vroom, janitor,
                 patchwork, tidyverse, devtools, ggpubr, ggpmisc, purrr, data.table)
  
  #calculate frequency
  df_formatted <- hped %>%
    pivot_longer(cols = starts_with(c("A", "B", "C","DQA1","DQB1",
                                      "DRB1","DPA1","DPB1")),
                 names_to = "Column", values_to = "alleles") %>%
    separate(Column, into = c("category", "haplotype"), sep = "\\.") %>%
    dplyr::rename(population = Population)
  
  pop_count <- df_formatted %>%
    group_by(population,category) %>%
    dplyr::summarise(total_alleles = n())
  
  allele_count <- df_formatted %>%
    filter(!is.na(alleles)) %>%
    group_by(population, alleles) %>%
    dplyr::summarise(allele_count = n()) %>%
    mutate(tmp_allele = alleles) %>%
    separate(tmp_allele, into = c("category", "spec"), sep = "\\*") %>%
    select(-spec)
  
  final = allele_count %>%
    inner_join(pop_count, by = c("population", "category")) %>%
    group_by(population, alleles) %>%
    dplyr::summarise(allele_freq = allele_count/total_alleles,
              allele_count = allele_count)
  
  tgt_al_freq  <- as_tibble(final) %>%
    separate(col = alleles, into = c("HLA_gene", NA), sep = "[*]", remove = F) %>%
    filter(HLA_gene == gene )
  tgt_al_freq  <<- tgt_al_freq
  
  #sort and rank
  sort_rank <- tgt_al_freq %>%
    group_by(population) %>%
    arrange(population, -allele_freq) %>%
    dplyr::mutate(
      Serial = row_number()
    ) %>%
    filter(Serial %in% c(1:ntop))
  
  #Extract unique values from the top alleles
  unic <- unique(sort_rank$alleles)
  
  #color code
  custom_colors5 <- c(colorRampPalette(RColorBrewer::brewer.pal(8, "Set2"))(length(unic)),"grey90")
  
  #plot
  tgt_al_freq %>%
    mutate(
      Label=if_else(alleles %in%  unic & allele_freq > 0.05, alleles, "others")) %>%
    group_by(population, Label) %>% dplyr::summarise(freq2 = sum(allele_freq)) %>%
    ggplot( aes(y=freq2, x=population, fill=Label)) +
    geom_bar(stat = "identity", show.legend = FALSE) +
    geom_text(aes(y = freq2,label = Label),
              position = position_stack(0.5),
              size = 4.5)+
    theme(legend.position = "none")+
    theme_classic()+
    labs(x = "Population", y = "Allele Frequency") +
    theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16),
          axis.title.x = element_text(size = 18), axis.title.y = element_text(size = 18)) +
    scale_fill_manual(values = custom_colors5)
}
```

Thanks!

**Comment by nanjalaruth** [comment]
> Hi, I was trying out your package and noticed I was getting some error messages with the default plot_HLA_Diversity function
> 
> ```
> Error in `n()`:
> ! Must only be used inside data-masking verbs like `mutate()`, `filter()`, and `group_by()`.
> ```
> 
> This is easily fixed by specifying the function to use should be dplyr::summarise(), so the new function would be:
> 
> ```
> plot_HLA_Diversity <-  function(hped, gene = "A", ntop = 2){
>    if(!require(pacman)) install.packages("pacman")
>   pacman::p_load(stringr, plyr, RColorBrewer, vroom, janitor,
>                  patchwork, tidyverse, devtools, ggpubr, ggpmisc, purrr, data.table)
>   
>   #calculate frequency
>   df_formatted <- hped %>%
>     pivot_longer(cols = starts_with(c("A", "B", "C","DQA1","DQB1",
>                                       "DRB1","DPA1","DPB1")),
>                  names_to = "Column", values_to = "alleles") %>%
>     separate(Column, into = c("category", "haplotype"), sep = "\\.") %>%
>     dplyr::rename(population = Population)
>   
>   pop_count <- df_formatted %>%
>     group_by(population,category) %>%
>     dplyr::summarise(total_alleles = n())
>   
>   allele_count <- df_formatted %>%
>     filter(!is.na(alleles)) %>%
>     group_by(population, alleles) %>%
>     dplyr::summarise(allele_count = n()) %>%
>     mutate(tmp_allele = alleles) %>%
>     separate(tmp_allele, into = c("category", "spec"), sep = "\\*") %>%
>     select(-spec)
>   
>   final = allele_count %>%
>     inner_join(pop_count, by = c("population", "category")) %>%
>     group_by(population, alleles) %>%
>     dplyr::summarise(allele_freq = allele_count/total_alleles,
>               allele_count = allele_count)
>   
>   tgt_al_freq  <- as_tibble(final) %>%
>     separate(col = alleles, into = c("HLA_gene", NA), sep = "[*]", remove = F) %>%
>     filter(HLA_gene == gene )
>   tgt_al_freq  <<- tgt_al_freq
>   
>   #sort and rank
>   sort_rank <- tgt_al_freq %>%
>     group_by(population) %>%
>     arrange(population, -allele_freq) %>%
>     dplyr::mutate(
>       Serial = row_number()
>     ) %>%
>     filter(Serial %in% c(1:ntop))
>   
>   #Extract unique values from the top alleles
>   unic <- unique(sort_rank$alleles)
>   
>   #color code
>   custom_colors5 <- c(colorRampPalette(RColorBrewer::brewer.pal(8, "Set2"))(length(unic)),"grey90")
>   
>   #plot
>   tgt_al_freq %>%
>     mutate(
>       Label=if_else(alleles %in%  unic & allele_freq > 0.05, alleles, "others")) %>%
>     group_by(population, Label) %>% dplyr::summarise(freq2 = sum(allele_freq)) %>%
>     ggplot( aes(y=freq2, x=population, fill=Label)) +
>     geom_bar(stat = "identity", show.legend = FALSE) +
>     geom_text(aes(y = freq2,label = Label),
>               position = position_stack(0.5),
>               size = 4.5)+
>     theme(legend.position = "none")+
>     theme_classic()+
>     labs(x = "Population", y = "Allele Frequency") +
>     theme(axis.text.x = element_text(size = 16), axis.text.y = element_text(size = 16),
>           axis.title.x = element_text(size = 18), axis.title.y = element_text(size = 18)) +
>     scale_fill_manual(values = custom_colors5)
> }
> ```
> 
> Thanks!

Thank you @iseultj
